name: 'terraform-plan'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

env:
  APP_ID: ${{ secrets.APP_ID }}
  TENENT_ID: ${{ secrets.TENENT_ID }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

jobs:
  terraform:
    name: 'test reusable workflow'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  plan:
    uses: ./.github/workflows/reusable.yml
    with:
      azure_client_id: ${{ env.APP_ID }}
      azure_tenant_id: ${{ env.TENENT_ID }}
      azure_subscription_id: ${{ env.SUBSCRIPTION_ID }}
      config-path: "."
      terraform-version: "1.3.2"
    secrets:
      token: ${{ secrets.CLIENT_SECRET }}

        
